[package]
name = "usaidwat"
version = "2.0.0-alpha.1"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
clap = { version = "4.5.38", features = ["derive"] }
colored = "3.0.0"
counter = "0.6.0"
htmlentity = "1.3.2"
indoc = "2.0.6"
pager = "0.16.1"
relativetime = "0.1.4"
reqwest = { version = "0.12.15", features = ["blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
textwrap = { version = "0.16.2", features = ["terminal_size"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
regex = "1.11.1"
uuid = { version = "1.16.0", features = ["v4"] }
